<?php
require_once __DIR__ . '/vendor/autoload.php';
function flat_annotation_viewer_api() {

    $parser = new MPI\EAF\Parser(__DIR__ . '/annotations/pear/pear2.eaf');
    $eaf    = $parser->parse();

    return drupal_json_output($eaf);
}

/**
 * hook_theme implementation
 *
 * @param array  $existing
 * @param string $type
 * @param string $theme
 * @param string $path
 *
 * @return array
 */
function flat_annotation_viewer_theme($existing, $type, $theme, $path) {

    return [

        'flat_annotation_viewer' => [
            'template' => 'theme/flat-annotation-viewer',
        ],
    ];
}

function flat_annotation_viewer() {

    $module_path = drupal_get_path('module', 'flat_annotation_viewer');

    drupal_add_css($module_path . '/annotation-viewer/dist/annotation-viewer/styles.css');

    drupal_add_js($module_path . '/annotation-viewer/dist/annotation-viewer/runtime-es2015.js', ['scope' => 'footer']);
    drupal_add_js($module_path . '/annotation-viewer/dist/annotation-viewer/polyfills-es2015.js', ['scope' => 'footer']);

    drupal_add_js($module_path . '/annotation-viewer/dist/annotation-viewer/runtime-es5.js', ['scope' => 'footer']);
    drupal_add_js($module_path . '/annotation-viewer/dist/annotation-viewer/polyfills-es5.js', ['scope' => 'footer']);

    drupal_add_js($module_path . '/annotation-viewer/dist/annotation-viewer/main-es2015.js', ['scope' => 'footer']);
    drupal_add_js($module_path . '/annotation-viewer/dist/annotation-viewer/main-es5.js', ['scope' => 'footer']);

    drupal_add_html_head([

        '#tag'        => 'base',
        '#attributes' => [
            'href' => '/' . request_uri(),
        ],

    ], 'annotation_viewer');

    return theme('flat_annotation_viewer');
}

function flat_annotation_viewer_menu() {

    $items = [];

    $items['islandora/object/%islandora_object/av'] = [

        'title'            => 'Annotation',
        'type'             => MENU_LOCAL_TASK,
        'page callback'    => 'flat_annotation_viewer',
        'page arguments'   => [2],
        'access callback'  => 'flat_annotation_viewer_menu_access',
        'access arguments' => [2],
        'weight'           => 100,
    ];

    $items['islandora/object/%islandora_object/av_api'] = [

        'title'           => 'FLAT Annotation Viewer',
        'type'            => MENU_CALLBACK,
        'page callback'   => 'flat_annotation_viewer_api',
        'page arguments'  => [2],
        'access callback' => 'flat_annotation_viewer_menu_access',
    ];

    return $items;
}

function flat_annotation_viewer_menu_access() {
    return true;
}
