<?php
require_once __DIR__ . '/vendor/autoload.php';
function flat_annotation_viewer() {

    $parser = new MPI\EAF\Parser(__DIR__ . '/annotations/pear/pear2.eaf');
    $eaf    = $parser->parse();

    return drupal_json_output($eaf);
}

function flat_annotation_viewer_menu() {

    $items = [];

    $items['islandora/object/%islandora_object/av'] = [

        'title'             => 'FLAT Annotation Viewer',
        'type'              => MENU_CALLBACK,
        'page callback'     => 'flat_annotation_viewer',
        'page arguments'    => [2],
        'access callback'   => 'flat_annotation_viewer_menu_access',
    ];

    return $items;
}

function flat_annotation_viewer_menu_access() {
    return true;
}
